export const SET_AVATAR_TO_CROPPER = 'SET_AVATAR_TO_CROPPER';
export const UPLOAD_AVATAR_PENDING = 'UPLOAD_AVATAR_PENDING';
export const UPLOAD_AVATAR_SUCCESS = 'UPLOAD_AVATAR_SUCCESS';
export const UPLOAD_AVATAR_ERROR = 'UPLOAD_AVATAR_ERROR';
