export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';
export const GET_SEARCH_RESULTS_SUCCESS = 'GET_SEARCH_RESULTS_SUCCESS';
export const CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS';
export const GET_MORE_RESULTS_SUCCESS = 'GET_MORE_RESULTS_SUCCESS';
export const ALL_RESULTS_LOADED = 'ALL_RESULTS_LOADED';
export const CLEAR_LOADED = 'CLEAR_LOADED';
export const ADD_NEXT_RESULTS = 'ADD_NEXT_RESULTS';
