export const GET_POST_PENDING = 'GET_POST_PENDING';
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';
export const GET_POST_ERROR = 'GET_POST_ERROR';
export const SET_CROPPED_IMAGE_FOR_POST = 'SET_CROPPED_IMAGE';
export const SET_DESCRIPTION_FOR_POST = 'SET_DESCRIPTION_FOR_POST';
export const RESET_ADD_POST = 'RESET_ADD_POST';
