export const CHECK_EMAIL_SET_EMAIL = "CHECK_EMAIL_SET_EMAIL";
export const CHECK_EMAIL_PENDING = "CHECK_EMAIL_PENDING";
export const CHECK_EMAIL_SUCCESS = "CHECK_EMAIL_SUCCESS";
export const CHECK_EMAIL_ERROR = "CHECK_EMAIL_ERROR";
