export const GET_USER_PENDING = 'GET_USER_PENDING';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_ERROR = 'GET_USER_ERROR';
export const DELETE_PHOTO_PENDING = 'DELETE_PHOTO_PENDING';
export const DELETE_PHOTO_SUCCESS = 'DELETE_PHOTO_SUCCESS';
export const DELETE_PHOTO_ERROR = 'ELETE_PHOTO_ERROR';
export const SET_PHOTO_TO_STATE = 'SET_PHOTO_TO_STATE';
