export const GET_USER_PENDING = 'GET_USER_PENDING';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_ERROR = 'GET_USER_ERROR';
export const DELETE_PHOTO_SUCCESS = 'DELETE_PHOTO_SUCCESS';
