export const REGISTER_SET_USERNAME = "REGISTER_SET_USERNAME";
export const REGISTER_SET_FULLNAME = "REGISTER_SET_FULLNAME";
export const REGISTER_SET_EMAIL = "REGISTER_SET_EMAIL";
export const REGISTER_SET_PASSWORD = "REGISTER_SET_PASSWORD";
export const REGISTER_USER = "REGISTER_USER";
