export const GET_LIKE_LIST_PENDING = 'GET_LIKE_LIST_PENDING';
export const GET_LIKE_LIST_SUCCESS = 'GET_LIKE_LIST_SUCCESS';
export const GET_MORE_LIKE_LIST_SUCCESS = 'GET_MORE_LIKE_LIST_SUCCESS';
export const ALL_LIKE_LIST_LOADED = 'ALL_LIKE_LIST_LOADED';
export const CLEAR_LIKE_LIST_LOADED = 'CLEAR_LIKE_LIST_LOADED';
export const UPLOAD_NEXT_LIKE_LIST = 'UPLOAD_NEXT_LIKE_LIST';
