export const GET_COMMENTS_PENDING = 'GET_COMMENTS_PENDING';
export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS';
export const ALL_COMMENTS_LOADED = 'ALL_COMMENTS_LOADED';
export const RESET_COMMENTS = 'RESET_COMMENTS';
export const EDIT_COMMENT = 'EDIT_COMMENT';
export const CHANGE_COMMENT = 'CHANGE_COMMENT';
export const CHANGE_EDIT_STATUS_COMMENT = 'CHANGE_EDIT_STATUS_COMMENT';
export const ADD_COMMENT_DISPATCH = 'ADD_COMMENT_DISPATCH';
