export const GET_COMMENTS = 'GET_COMMENTS';
export const GET_COMMENTS_PENDING = 'GET_COMMENTS_PENDING';
export const ALL_COMMENTS_LOADED = 'ALL_COMMENTS_LOADED';
export const ADD_NEXT_COMMENTS_PAGE = 'ADD_NEXT_COMMENTS_PAGE';
export const GET_MORE_COMMENTS_SUCCESS = 'GET_MORE_COMMENTS_SUCCESS';
export const RESET_COMMENTS = 'RESET_COMMENTS';
