export const SET_FOLLOWING_PENDING = 'SET_FOLLOWING_PENDING';
export const SET_FOLLOWING = 'SET_SET_FOLLOWING';
export const SET_NEXT_PAGE = 'SET_NEXT_PAGE';
export const SET_MORE_FOLLOWING = 'SET_MORE_FOLLOWING';
export const ALL_FOLLOWING_LOADED = 'ALL_FOLLOWING_LOADED';
