export const SET_POST_AUTHORS_OF_LIKES = 'SET_POST_AUTHORS_OF_LIKES';
export const SET_FEED_AUTHORS_OF_LIKES = 'SET_FEED_AUTHORS_OF_LIKES';
export const CHECK_LOGGED_USER_LIKE_EXIST = 'CHECK_LOGGED_USER_LIKE_EXIST';
export const ADD_USER_LIKE = 'ADD_USER_LIKE';
export const REMOVE_USER_LIKE = 'REMOVE_USER_LIKE';
export const ADD_FEED_USER_LIKE = 'ADD_FEED_USER_LIKE';
export const REMOVE_FEED_USER_LIKE = 'REMOVE_FEED_USER_LIKE';
