export const SET_FOLLOWERS_PENDING = 'SET_FOLLOWERS_PENDING';
export const SET_FOLLOWERS = 'SET_FOLLOWERS';
export const SET_NEXT_PAGE = 'SET_NEXT_PAGE';
export const SET_MORE_FOLLOWERS = 'SET_MORE_FOLLOWERS';
export const ALL_FOLLOWERS_LOADED = 'ALL_FOLLOWERS_LOADED';
export const CHANGE_USER_FOLLOWING = 'CHANGE_USER_FOLLOWING';
