export const GET_MENTION_LIST_PENDING = 'GET_MENTION_LIST_PENDING';
export const GET_MENTION_LIST_SUCCESS = 'GET_MENTION_LIST_SUCCESS';
export const GET_MORE_MENTION_LIST_SUCCESS = 'GET_MORE_MENTION_LIST_SUCCESS';
export const ALL_MENTION_LIST_LOADED = 'ALL_MENTION_LIST_LOADED';
export const CLEAR_MENTION_LIST_LOADED = 'CLEAR_MENTION_LIST_LOADED';
export const UPLOAD_NEXT_MENTION_LIST = 'UPLOAD_NEXT_MENTION_LIST';
