export const SET_SUBSCRIBERS_PENDING = 'SET_SUBSCRIBERS_PENDING';
export const SET_SUBSCRIBERS = 'SET_SUBSCRIBERS';
export const SET_SUBSCRIBERS_COUNT = 'SET_SUBSCRIBERS_COUNT';
export const ALL_SUBSCRIBERS_LOADED = 'ALL_SUBSCRIBERS_LOADED';
export const CHANGE_USER_FOLLOWING = 'CHANGE_USER_FOLLOWING';
export const RESET_SUBSCRIBERS = 'RESET_SUBSCRIBERS';
