export const GET_POSTS_PENDING = 'GET_POSTS_PENDING';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_MORE_POSTS_SUCCESS = 'GET_MORE_POSTS_SUCCESS';
export const ALL_POSTS_LOADED = 'ALL_POSTS_LOADED';
export const CLEAR_LOADED = 'CLEAR_LOADED';
export const SHOW_POST = 'SHOW_POST';
export const ADD_OR_REMOVE_AUTHOR_OF_LIKE = 'ADD_OR_REMOVE_AUTHOR_OF_LIKE';
