export const GET_POSTS_PENDING = 'GET_POSTS_PENDING';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_MORE_POSTS_SUCCESS = 'GET_MORE_POSTS_SUCCESS';
export const GET_POSTS_ERROR = 'GET_POSTS_ERROR';
export const ALL_POSTS_LOADED = 'ALL_POSTS_LOADED';
export const CLEAR_LOADED = 'CLEAR_LOADED';
