export const GET_POSTS_PENDING = 'GET_POSTS_PENDING';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_MORE_POSTS_SUCCESS = 'GET_MORE_POSTS_SUCCESS';
export const ALL_POSTS_LOADED = 'ALL_POSTS_LOADED';
export const CLEAR_LOADED = 'CLEAR_LOADED';
export const DELETE_POST_PENDING = 'DELETE_POST_PENDING';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const SHOW_SELECTED_POST = 'SHOW_SELECTED_POST';
