export const GET_NEWS_FEED_PENDING = 'GET_NEWS_FEED_PENDING';
export const GET_NEWS_FEED_SUCCESS = 'GET_NEWS_FEED_SUCCESS';
export const GET_MORE_NEWS_FEED_SUCCESS = 'GET_MORE_NEWS_FEED_SUCCESS';
export const ALL_NEWS_FEED_LOADED = 'ALL_NEWS_FEED_LOADED';
export const CLEAR_NEWS_FEED_LOADED = 'CLEAR_NEWS_FEED_LOADED';
